import { Vacature, Kandidaat, Sollicitatie, Contract } from './types'

export const vacatures: Vacature[] = [
  {
    id: 'vac-1',
    title: 'Marketing Manager',
    company: 'TechVentures B.V.',
    location: 'Amsterdam',
    land: 'Nederland',
    vakgebied: 'Marketing & E-commerce',
    salaris: '€4.500 - €6.000',
    deadline: '2026-04-15',
    status: 'open',
    createdAt: '2026-03-01',
    pmsCompleted: true,
    hardeCriteria: {
      opleidingsniveau: 'HBO',
      minimaleErvaring: '5-10 jaar',
      locatie: 'Amsterdam',
      opKantoor: 'Hybride (3 dagen)',
      maxReistijd: '45 minuten',
    },
    kandidaten: [
      {
        id: 'k-1', naam: 'Anna de Jong', initialen: 'A', anoniem: false,
        hardeCriteriaMatch: 100, hardeCriteriaIcon: 'check',
        deVriesFit: 87, scoutRating: 4.9, scoutNaam: 'Sophie de Graaf', scoutId: 'scout-1',
        status: 'aanbevolen', procesStatus: 'arbeidsvoorwaarden', unlocked: true,
        opleidingsniveau: 'WO', werkervaring: '8 jaar', woonplaats: 'Amsterdam',
        email: 'anna.dejong@email.nl', telefoon: '06-12345678',
        gesprekken: [
          { id: 'g-1', type: 'kennismaking', datum: '2026-03-10', feedback: 'Zeer sterke kandidaat. Goede culturele fit, enthousiast over de rol. Inhoudelijk sterk.', rating: 5, status: 'afgerond' },
          { id: 'g-2', type: 'verdieping', datum: '2026-03-14', feedback: 'Team was ook enthousiast. Past goed bij de bedrijfscultuur.', rating: 5, status: 'afgerond' },
        ],
      },
      {
        id: 'k-2', naam: 'Jamal Usan', initialen: 'M', anoniem: true,
        hardeCriteriaMatch: 92, hardeCriteriaIcon: 'check',
        deVriesFit: 71, scoutRating: 4.1, scoutNaam: 'Sophie de Graaf', scoutId: 'scout-1',
        status: 'bekijk', procesStatus: 'voorgesteld', unlocked: false,
        opleidingsniveau: 'HBO', werkervaring: '6 jaar', woonplaats: 'Utrecht',
      },
      {
        id: 'k-3', naam: 'Lisa Brouwer', initialen: 'L', anoniem: true,
        hardeCriteriaMatch: 76, hardeCriteriaIcon: 'warning',
        deVriesFit: 53, scoutRating: 3.2, scoutNaam: 'Mark Jansen', scoutId: 'scout-2',
        status: 'overweeg', procesStatus: 'voorgesteld', unlocked: false,
        opleidingsniveau: 'HBO', werkervaring: '4 jaar', woonplaats: 'Den Haag',
      },
    ],
  },
  {
    id: 'vac-2',
    title: 'Senior Software Developer',
    company: 'TechVentures B.V.',
    location: 'Amsterdam / Remote',
    land: 'Nederland',
    vakgebied: 'ICT & Development',
    salaris: '€5.500 - €7.500',
    deadline: '2026-04-30',
    status: 'open',
    createdAt: '2026-03-10',
    pmsCompleted: true,
    hardeCriteria: {
      opleidingsniveau: 'HBO',
      minimaleErvaring: '5-10 jaar',
      locatie: 'Amsterdam / Remote',
      opKantoor: 'Hybride (2 dagen)',
      maxReistijd: '60 minuten',
    },
    kandidaten: [
      {
        id: 'k-4', naam: 'Thomas van Dijk', initialen: 'T', anoniem: false,
        hardeCriteriaMatch: 95, hardeCriteriaIcon: 'check',
        deVriesFit: 82, scoutRating: 4.5, scoutNaam: 'Sophie de Graaf', scoutId: 'scout-1',
        status: 'aanbevolen', procesStatus: 'gesprek_plannen', unlocked: true,
        opleidingsniveau: 'WO', werkervaring: '10 jaar', woonplaats: 'Amsterdam',
        email: 'thomas.vdijk@email.nl', telefoon: '06-34567890',
        gesprekken: [],
      },
      {
        id: 'k-5', naam: 'Priya Sharma', initialen: 'P', anoniem: true,
        hardeCriteriaMatch: 88, hardeCriteriaIcon: 'check',
        deVriesFit: 68, scoutRating: 3.8, scoutNaam: 'Mark Jansen', scoutId: 'scout-2',
        status: 'bekijk', procesStatus: 'feedback_geven', unlocked: true,
        opleidingsniveau: 'HBO', werkervaring: '7 jaar', woonplaats: 'Rotterdam',
        email: 'priya.sharma@email.nl', telefoon: '06-45678901',
        gesprekken: [
          { id: 'g-3', type: 'kennismaking', datum: '2026-03-12', status: 'afgerond' },
        ],
      },
    ],
  },
]

export const allVacatures: Vacature[] = [
  ...vacatures,
  {
    id: 'vac-3',
    title: 'HR Business Partner',
    company: 'GreenLogistics B.V.',
    location: 'Rotterdam',
    land: 'Nederland',
    vakgebied: 'HR & Recruitment',
    salaris: '€4.000 - €5.500',
    deadline: '2026-04-20',
    status: 'open',
    createdAt: '2026-03-05',
    pmsCompleted: true,
    hardeCriteria: {
      opleidingsniveau: 'HBO',
      minimaleErvaring: '2-5 jaar',
      locatie: 'Rotterdam',
      opKantoor: 'Op kantoor (5 dagen)',
      maxReistijd: '30 minuten',
    },
    kandidaten: [],
  },
  {
    id: 'vac-4',
    title: 'Financial Controller',
    company: 'MedTech Solutions',
    location: 'Eindhoven',
    land: 'Nederland',
    vakgebied: 'Accountancy & Finance',
    salaris: '€5.000 - €6.500',
    deadline: '2026-05-01',
    status: 'open',
    createdAt: '2026-03-12',
    pmsCompleted: true,
    hardeCriteria: {
      opleidingsniveau: 'WO',
      minimaleErvaring: '5-10 jaar',
      locatie: 'Eindhoven',
      opKantoor: 'Hybride (3 dagen)',
      maxReistijd: '45 minuten',
    },
    kandidaten: [],
  },
]

// ─── Archived (completed) vacatures ──────────────────────────────────────────
export const archiefVacatures: Vacature[] = [
  {
    id: 'vac-arch-1',
    title: 'Product Owner',
    company: 'TechVentures B.V.',
    location: 'Amsterdam',
    land: 'Nederland',
    vakgebied: 'ICT & Development',
    salaris: '€4.500 - €6.000',
    deadline: '2025-09-15',
    status: 'vervuld',
    createdAt: '2025-06-01',
    pmsCompleted: true,
    hardeCriteria: {
      opleidingsniveau: 'HBO',
      minimaleErvaring: '5-10 jaar',
      locatie: 'Amsterdam',
      opKantoor: 'Hybride (3 dagen)',
      maxReistijd: '45 minuten',
    },
    kandidaten: [
      {
        id: 'k-arch-1', naam: 'Sanne Visser', initialen: 'S', anoniem: false,
        hardeCriteriaMatch: 100, hardeCriteriaIcon: 'check',
        deVriesFit: 74, scoutRating: 3.8, scoutNaam: 'Mark Jansen', scoutId: 'scout-2',
        status: 'aangenomen', procesStatus: 'contract_getekend', unlocked: true,
        opleidingsniveau: 'HBO', werkervaring: '7 jaar', woonplaats: 'Amsterdam',
        email: 'sanne.visser@email.nl', telefoon: '06-55566677',
        contractDatum: '2025-08-20',
      },
    ],
  },
  {
    id: 'vac-arch-2',
    title: 'Digital Marketing Lead',
    company: 'TechVentures B.V.',
    location: 'Amsterdam',
    land: 'Nederland',
    vakgebied: 'Marketing & E-commerce',
    salaris: '€4.000 - €5.500',
    deadline: '2025-12-01',
    status: 'vervuld',
    createdAt: '2025-09-15',
    pmsCompleted: true,
    hardeCriteria: {
      opleidingsniveau: 'HBO',
      minimaleErvaring: '2-5 jaar',
      locatie: 'Amsterdam',
      opKantoor: 'Hybride (2 dagen)',
      maxReistijd: '60 minuten',
    },
    kandidaten: [
      {
        id: 'k-arch-2', naam: 'Jamal Usan', initialen: 'J', anoniem: false,
        hardeCriteriaMatch: 92, hardeCriteriaIcon: 'check',
        deVriesFit: 71, scoutRating: 4.1, scoutNaam: 'Sophie de Graaf', scoutId: 'scout-1',
        status: 'aangenomen', procesStatus: 'contract_getekend', unlocked: true,
        opleidingsniveau: 'HBO', werkervaring: '6 jaar', woonplaats: 'Utrecht',
        email: 'jamal.usan@email.nl', telefoon: '06-23456789',
        contractDatum: '2025-11-10',
      },
    ],
  },
]

export const scoutKandidaten: Kandidaat[] = [
  // === BESCHIKBAAR ===
  {
    id: 'k-6', naam: 'Eva Bakker', email: 'eva.bakker@email.nl',
    telefoon: '06-45678901', woonplaats: 'Haarlem',
    opleidingsniveau: 'HBO', werkervaring: '3 jaar',
    huidigeRol: 'Junior Accountant',
    voorkeursFunctie: 'Financial Controller',
    scanCompleted: false, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'beschikbaar',
  },
  {
    id: 'k-7', naam: 'Sophie Vermeer', email: 'sophie.vermeer@email.nl',
    telefoon: '06-56789012', woonplaats: 'Den Haag',
    opleidingsniveau: 'WO', werkervaring: '5 jaar',
    huidigeRol: 'HR Business Partner bij MediaGroup',
    voorkeursFunctie: 'HR Manager',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'beschikbaar',
  },
  {
    id: 'k-8', naam: 'Daan Hendriks', email: 'daan.hendriks@email.nl',
    telefoon: '06-67890123', woonplaats: 'Rotterdam',
    opleidingsniveau: 'HBO', werkervaring: '4 jaar',
    huidigeRol: 'Frontend Developer bij StartupX',
    voorkeursFunctie: 'Full Stack Developer',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'beschikbaar',
  },
  {
    id: 'k-9', naam: 'Fatima El Amrani', email: 'fatima.elamrani@email.nl',
    telefoon: '06-78901234', woonplaats: 'Amsterdam',
    opleidingsniveau: 'WO', werkervaring: '7 jaar',
    huidigeRol: 'Data Analyst bij ConsultCo',
    voorkeursFunctie: 'Data Science Lead',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'beschikbaar',
  },
  {
    id: 'k-10', naam: 'Lars de Boer', email: 'lars.deboer@email.nl',
    telefoon: '06-89012345', woonplaats: 'Eindhoven',
    opleidingsniveau: 'HBO', werkervaring: '2 jaar',
    huidigeRol: 'Junior Sales Executive bij TechSales',
    voorkeursFunctie: 'Account Manager',
    scanCompleted: true, cvUploaded: false, scoutId: 'scout-1',
    poolStatus: 'beschikbaar',
  },
  // === GEPLAATST ===
  {
    id: 'k-1', naam: 'Anna de Jong', email: 'anna.dejong@email.nl',
    telefoon: '06-12345678', woonplaats: 'Amsterdam',
    opleidingsniveau: 'WO', werkervaring: '8 jaar',
    huidigeRol: 'Marketing Manager bij TechVentures B.V.',
    voorkeursFunctie: 'Marketing Manager',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'geplaatst',
    plaatsing: { vacatureTitle: 'Marketing Manager', bedrijf: 'TechVentures B.V.', datum: '2026-02-15', fee: 10800, scoutFee: 5400 },
  },
  {
    id: 'k-2', naam: 'Jamal Usan', email: 'jamal.usan@email.nl',
    telefoon: '06-23456789', woonplaats: 'Utrecht',
    opleidingsniveau: 'HBO', werkervaring: '6 jaar',
    huidigeRol: 'Marketing Specialist bij BrandHouse',
    voorkeursFunctie: 'Marketing Manager',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'geplaatst',
    plaatsing: { vacatureTitle: 'Digital Marketing Lead', bedrijf: 'BrandHouse B.V.', datum: '2026-01-20', fee: 7200, scoutFee: 3600 },
  },
  {
    id: 'k-4', naam: 'Thomas van Dijk', email: 'thomas.vdijk@email.nl',
    telefoon: '06-34567890', woonplaats: 'Amsterdam',
    opleidingsniveau: 'WO', werkervaring: '10 jaar',
    huidigeRol: 'Senior Developer bij FinTechCo',
    voorkeursFunctie: 'Senior Software Developer',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'geplaatst',
    plaatsing: { vacatureTitle: 'Lead Software Engineer', bedrijf: 'FinTechCo', datum: '2025-11-10', fee: 12000, scoutFee: 6000 },
  },
  // === INACTIEF ===
  {
    id: 'k-11', naam: 'Roos van der Berg', email: 'roos.vdberg@email.nl',
    telefoon: '06-90123456', woonplaats: 'Groningen',
    opleidingsniveau: 'WO', werkervaring: '6 jaar',
    huidigeRol: 'UX Designer bij DesignStudio',
    voorkeursFunctie: 'Senior UX Designer',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'inactief',
    inactiefReden: 'Zelf teruggetrokken — ander aanbod geaccepteerd',
    inactiefDatum: '2026-03-05',
  },
  {
    id: 'k-12', naam: 'Pieter Jansen', email: 'pieter.jansen@email.nl',
    telefoon: '06-01234567', woonplaats: 'Leiden',
    opleidingsniveau: 'HBO', werkervaring: '9 jaar',
    huidigeRol: 'Operations Manager bij LogiCorp',
    voorkeursFunctie: 'Operations Director',
    scanCompleted: true, cvUploaded: true, scoutId: 'scout-1',
    poolStatus: 'inactief',
    inactiefReden: 'Tijdelijk niet beschikbaar — persoonlijke redenen',
    inactiefDatum: '2026-02-28',
  },
]

export const kandidaatSollicitaties: Sollicitatie[] = [
  { id: 's-1', vacatureTitle: 'Marketing Manager', company: 'TechVentures B.V.', status: 'Arbeidsvoorwaarden', datum: '2026-03-08', procesStatus: 'arbeidsvoorwaarden', vacatureId: 'vac-1' },
  { id: 's-2', vacatureTitle: 'Brand Strategist', company: 'CreativeCo', status: 'In behandeling', datum: '2026-03-12', procesStatus: 'gesprek_gepland', vacatureId: 'vac-ext-1' },
]

export function calculateFee(opleidingsniveau: string, werkervaring: string): { fee: number; scoutFee: number; refurzyFee: number } {
  const expPoints: Record<string, number> = { '0-2 jaar': 1, '2-5 jaar': 2, '5-10 jaar': 3, '>10 jaar': 4 }
  const eduPoints: Record<string, number> = { 'MBO': 1.5, 'HBO': 2, 'WO': 3 }
  const exp = expPoints[werkervaring] || 2
  const edu = eduPoints[opleidingsniveau] || 2
  const fee = exp * edu * 1200
  return { fee, scoutFee: fee * 0.5, refurzyFee: fee * 0.5 }
}

// ─── Mock contracts ─────────────────────────────────────────────────────────
export const mockContracten: Contract[] = [
  {
    id: 'contract-1',
    contractNummer: 'RF-2026-001',
    datum: '2026-02-15',
    opdrachtgeverNaam: 'Daan Verhoeven',
    opdrachtgeverBedrijf: 'TechVentures B.V.',
    opdrachtgeverKvk: '12345678',
    opdrachtgeverAdres: 'Herengracht 100, 1015 BS Amsterdam',
    vacatureId: 'vac-1',
    vacatureTitle: 'Marketing Manager',
    kandidaatId: 'k-1',
    kandidaatNaam: 'Anna de Jong',
    kandidaatInitialen: 'A',
    scoutNaam: 'Sophie de Graaf',
    opleidingsniveau: 'WO',
    werkervaring: '8 jaar',
    plaatsingsfee: 10800,
    btw: 2268,
    totaalInclBtw: 13068,
    scoutFee: 5400,
    fitGarantie: true,
    mScore: 87,
    status: 'actief',
    ondertekendDoor: 'Daan Verhoeven',
    ondertekendOp: '2026-02-15T14:32:00Z',
  },
  {
    id: 'contract-2',
    contractNummer: 'RF-2026-002',
    datum: '2026-03-05',
    opdrachtgeverNaam: 'Daan Verhoeven',
    opdrachtgeverBedrijf: 'TechVentures B.V.',
    opdrachtgeverKvk: '12345678',
    opdrachtgeverAdres: 'Herengracht 100, 1015 BS Amsterdam',
    vacatureId: 'vac-2',
    vacatureTitle: 'Senior Software Developer',
    kandidaatId: 'k-4',
    kandidaatNaam: 'Thomas van Dijk',
    kandidaatInitialen: 'T',
    scoutNaam: 'Sophie de Graaf',
    opleidingsniveau: 'WO',
    werkervaring: '10 jaar',
    plaatsingsfee: 14400,
    btw: 3024,
    totaalInclBtw: 17424,
    scoutFee: 7200,
    fitGarantie: true,
    mScore: 82,
    status: 'getekend',
    ondertekendDoor: 'Daan Verhoeven',
    ondertekendOp: '2026-03-05T10:15:00Z',
  },
  {
    id: 'contract-3',
    contractNummer: 'RF-2025-047',
    datum: '2025-06-20',
    opdrachtgeverNaam: 'Daan Verhoeven',
    opdrachtgeverBedrijf: 'TechVentures B.V.',
    opdrachtgeverKvk: '12345678',
    opdrachtgeverAdres: 'Herengracht 100, 1015 BS Amsterdam',
    vacatureId: 'vac-old-1',
    vacatureTitle: 'Product Owner',
    kandidaatId: 'k-old-1',
    kandidaatNaam: 'Sanne Visser',
    kandidaatInitialen: 'S',
    scoutNaam: 'Mark Jansen',
    opleidingsniveau: 'HBO',
    werkervaring: '5-10 jaar',
    plaatsingsfee: 7200,
    btw: 1512,
    totaalInclBtw: 8712,
    scoutFee: 3600,
    fitGarantie: false,
    mScore: 74,
    status: 'verlopen',
    ondertekendDoor: 'Daan Verhoeven',
    ondertekendOp: '2025-06-20T09:00:00Z',
  },
]

// ─── Pipeline step definitions ──────────────────────────────────────────────
export const pipelineSteps = [
  { key: 'voorgesteld', label: 'Voorgesteld', icon: '📋', color: 'text-ink-muted' },
  { key: 'contract_akkoord', label: 'Contract akkoord', icon: '✅', color: 'text-purple' },
  { key: 'gesprek_plannen', label: 'Gesprek plannen', icon: '📅', color: 'text-orange' },
  { key: 'gesprek_gepland', label: 'Gesprek gepland', icon: '🤝', color: 'text-blue-500' },
  { key: 'feedback_geven', label: 'Feedback geven', icon: '💬', color: 'text-yellow-600' },
  { key: 'vervolggesprek', label: 'Vervolggesprek', icon: '🔄', color: 'text-blue-500' },
  { key: 'arbeidsvoorwaarden', label: 'Arbeidsvoorwaarden', icon: '💼', color: 'text-purple' },
  { key: 'contract_getekend', label: 'Contract getekend', icon: '🎉', color: 'text-green-600' },
] as const

export const afwijzingsRedenen = [
  { key: 'ervaring', label: 'Niet de juiste ervaring' },
  { key: 'cultuur', label: 'Culturele mismatch' },
  { key: 'salaris', label: 'Salariseis te hoog' },
  { key: 'andere_kandidaat', label: 'Andere kandidaat gekozen' },
  { key: 'anders', label: 'Anders' },
] as const
